per_listener_settings false

listener 1883 0.0.0.0
protocol mqtt

allow_anonymous false
password_file /mosquitto/config/passwords
acl_file /mosquitto/config/aclfile

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_dest file /mosquitto/log/mosquitto.log
log_timestamp true
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
